apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: node-web
  ports:
    - name: node-web
      protocol: TCP
      port: 3000
      targetPort: 3000